[package]
name = "meshtools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.3"
eframe = "0.19.0"
egui = "0.19.0"
nalgebra-glm = "0.17.0"
rfd = "0.10.0"
